## LaraHelpers

- `rishadblack/larahelpers` provides global helper functions (number and currency formatting, compact lakh/crore numbers, number-to-words in English and Bangla, Bangla dates, fiscal years, Bangladeshi phone numbers, masking and initials, branding asset URLs, request and locale helpers, file sizes). Activate the `larahelpers-development` skill before calling, changing or testing any of them.
- Prefer these helpers over ad-hoc `number_format()` / `asset()` calls when the app already uses them, so output stays consistent: `numberFormat()`, `pointFormat()`, `unitFormat()`, `percentFormat()`, `compactNumber()`, `asset_logo()`, `asset_storage()`, and so on.
- For amounts in words on invoices and vouchers use `numberToWords($amount)`: it follows `app()->getLocale()` (`en` or `bn`), uses lakh/crore in English and reads decimals as `TAKA AND ... PAISA ONLY`. `banglaDate($date)` renders dates with Bangla names and digits, `fiscalYear($date)` returns the July–June year as `label`, `start` and `end`, and `formatBdPhone($phone)` normalises mobile numbers (returns `null` when invalid).
- `numberFormat($value, $sign = false, $decimal = false, $thousand = '')` strips non-numeric characters, defaults to 2 decimals and **no** thousand separator; pass `$thousand = ','` for `1,234.57`, `$decimal = true` for no decimals, and `$sign = true` to append `currencySymbol()` (which always uses `,` grouping: `1,234.57 ৳`).
- `currencySymbol()`, `pointFormat()`, `numberToWords()`, `fiscalYear()` and the `asset_*()` helpers read `config('app.currency_symbol')`, `config('app.point_sign')`, `config('app.currency_name')`, `config('app.currency_fraction_name')`, `config('app.fiscal_year_start_month')`, `config('app.logo')`, `config('app.dark_logo')`, `config('app.logo_powered')`, `config('app.favicon')` and `config('app.default_profile_picture')`. Add those keys to `config/app.php` when you use the helpers; they are not shipped by the package.
- Every function is wrapped in `function_exists()`. Do not declare app helpers with the same names; pick distinct names instead of relying on load order.
- The helpers call `config()`, `request()`, `app()` and `asset()`, so test them in feature tests (not unit tests), set config with `config()->set()` and swap the request with `app()->instance('request', Request::create(...))`.
